#ifndef CONFIG_H
#define CONFIG_H

#define PANC_MAX_DEVICES 1
#define PANC_MAX_CONCURRENT_REASSEMBLIES 1
#define PANC_TESTS_ENABLED 0
#define PANC_HELPERS_ENABLED 0
#define PANC_HAVE_PRINTF 0
#define PANC_BIG_ENDIAN 0
#define PANC_DEMO_TWO 0
#define PANC_USE_COLOR 0

#endif
