#ifndef CONFIG_H
#define CONFIG_H

#define PANC_MAX_DEVICES 1
#define PANC_MAX_CONCURRENT_REASSEMBLIES 2
#define PANC_TESTS_ENABLED 1
#define PANC_HELPERS_ENABLED 1
#define PANC_HAVE_PRINTF 1

#endif
